language: 
  - java
  - node_js
jdk:
  - oraclejdk8
node_js:
  - "6"
services:
  - mysql
env:
  global:
  - VERSION=0.1.0
  - secure: ebIkXqkIYqIfkCkm1jUc2MA/lkld7n4+4mEajjiM2wuJloIcoY5elDMZxLw0i3LWCJBCQIHd4+TR24+CFkgalSheHrGNCPUzYmh6neszo325avNaJO2py5CaO6/EMzmreMvWRw52HfRulwqORFh1VucEo/4PKKgxvZOfDEsVYYZj/pQ+oPlnJnDLIwXZKw9RLKURVt/zKI2vuY4xxzTZCnSNYbPmyYWpvRHzWTs//3jfKxsakiMEIFKEoTRw/jYzixI2T8PGodryBCglDwQm6E0hC7zmUAoqZyujTUMXFtJlWqHJCHu7sicmchPUJRPU8MQ3PNyDUIGe4bQFV8DSXiOtsLS/XXQUFQhtSTsfFSKuIzjxYt7CIO7GUq719GzZgcNH/ncJ1TaNl+AOx0FmcUjOZ9i7iig+vGY05PBX8YRAt2rw23xSWh6koVRSvqt+pGaZVDdM0rpVDW45DjmC1+fpbPbAP4NJq/boVuUPdTp1wPAQV70ANdU43YHEap8pyir5aFP657Ic8BhldbKWRmtPRMsBQZ06ryRFUD42ljaPLnIt+ATdaCOWOBCmzO4C4pjjmUoqru0YJiV5BG6PcQBF2A0SPdF8n+Ms7+HFte9FspXvuhW8gTUYVLaG2oL69VLcDnXnjzYiSnRGl3S9gALV3TmAd6tqrF0+N99ilTA=
  - secure: WJofnh72rv37DOV/2YjCSdZ0BI+NWeWQ2DIR4d4UM6kZB/lWpt2YqFfDYbYm9qthcwy3uCo1t+CB9WdnvC8x8KE0H8V2eCT03tW03jcdsOZeVj5H1kFCy5vUUyH5XTqmFCxoou/La/+hM7he9xZw9zOhx/lu0LccbyN7+oXAcQBAnLbZhG7JB4D+LEibWdkuIthpXAag5096c14RNr3sJBM7YMIwMmXBOfFtXSKrS7y35RQLV+W9O8xm3ooAXBIAmXLc1hynwkX/x5iMoNFWbWjPHVDHJ/I/Gpi+oUUxtLO6rSqGd6GkQpNHPXnH4BZ7rQt6MEFHNLHZCa6g+Nwrqv7ZtkI8JUb1MdzvF/GK7xSQEIUkhQsPjfsTrKCieJ9mObPdbs5DXW3ZqCKLW0SpLK+Z1eqFqb7JSE8DvUZiM62TJspxW7mOdaHSjl99uggVxyrbqHoYeZz0f6LSE6Xfm3UZzoFBTJulnHfQWCA7WqOOokmW4ubDJp2pPwFlXAyoXCC3fTMRo3zIssUJy0kmftj1jxCMqBGeqOpjk6O2BAgRB490SdCath1soM3DMccwzg5WkWktVeyTP6qyY7ffN+in3PadcVJTZL7yIZE0a2OQub/1Z7gO5volTfSqBru6LdWV/CGMLgSJzGfKeGUh5jos4KG6nJwRLhQcKSwSIno=
before_install:
  - npm install apidoc -g
  - mysql -u root -e 'create database oniri_test;'
script:
  - mvn test
  - mvn javadoc:javadoc
  - apidoc -o target/site/restapidocs
after_success:
  - cd target/site/apidocs/
  - find -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://ftp.cluster007.ovh.net/doc/oniri/java/$TRAVIS_BRANCH/$VERSION/{} \;
  - find -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://ftp.cluster007.ovh.net/doc/oniri/java/$TRAVIS_BRANCH/latest/{} \;
  - cd ../restapidocs/
  - find -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://ftp.cluster007.ovh.net/doc/oniri/rest/$TRAVIS_BRANCH/$VERSION/{} \;
  - find -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://ftp.cluster007.ovh.net/doc/oniri/rest/$TRAVIS_BRANCH/latest/{} \;
  - cd ../../..
  - mvn clean cobertura:cobertura coveralls:report
